### ISSUE TITLE
Edit profile button leads to this

### ISSUE THREAD

**Issue by MitchellArtz** [launchtechllc/w3hacks#22]
![image](https://user-images.githubusercontent.com/32065190/86939069-1dfcd300-c10f-11ea-9457-81a90193729b.png)

**Comment by angelachenn** [comment]
Reproducible on Macbook Air Catalina + Google Chrome, with a different result.
<img width="558" alt="Screen Shot 2020-07-08 at 9 08 50 PM" src="https://user-images.githubusercontent.com/65053157/86985435-3ac0f700-c15f-11ea-9f75-b57d6f4adf39.png">
